#!/bin/sh

set -e -x

# Kernel Source
KERNEL_SOURCE=https://github.com/RN10S-Development/kernel_redmi_rosemary
KERNEL_BRANCH=lineage-20
KERNEL_DEFCONFIG=rosemary_defconfig

# Prebuilt Proton Clang Toolchain
CLANG=https://github.com/LineageOS/android_prebuilts_clang_kernel_linux-x86_clang-r416183b
CLANG_BRANCH=lineage-20.0

# Setup make Command
make_fun() {
  make O=out ARCH=arm64 CC=clang \
  LLVM=1 LLVM_IAS=1 \
  CROSS_COMPILE_ARM32=arm-linux-gnueabi- "$@"
}

# Work Path
WORK=${HOME}/work

# Kernel Folder Name
KERNEL=android-kernel

# Kernel Source Path
KERNEL_SRC=${WORK}/${KERNEL}

# Prepare Directory
mkdir -p "${WORK}"
cd "${WORK}" || exit 1

# Cloning all the Necessary files
[ ! -d clang ] && git clone --depth=1 "${CLANG}" -b "${CLANG_BRANCH}" ./clang
[ ! -d "${KERNEL}" ] && git clone --depth=1 "${KERNEL_SOURCE}" -b "${KERNEL_BRANCH}" "${KERNEL}"

# Setting Toolchain Path
PATH="${WORK}/clang/bin:$PATH"
alias ld=ld.lld

# Enter Kernel root directory
cd "${KERNEL_SRC}" || exit 1

# Start Compiling Kernel
make_fun "${KERNEL_DEFCONFIG}"
make_fun -j"$(nproc --all)" 2>&1 | tee build.log || exit 1
